services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: pimp-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Pimp_Strong_Pass123"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - pimp_data:/var/opt/mssql

volumes:
  pimp_data:
